### PR TITLE
Centralize results

### PR DESCRIPTION
**Pull request by krikmo**
This opens `<center>` for [this](https://github.com/alexwlchan/hurley/blob/master/hurley/templates/index.html#L41) line.

### CODE REVIEW

**Comment by Foggalong** [comment]
`<center>` is a deprecated tag now, ideally it should be done with CSS instead. The branches have also messed up - the show commit shouldn't be in this pull also

**Comment by krikmo** [comment]
OK. I sent on a different branch to differentiate from [#8](https://github.com/alexwlchan/hurley/pull/8), otherwise it would just show up there. The show commit is there because [master](https://github.com/alexwlchan/hurley) is behind [results](https://github.com/krikmo/hurley/tree/results), right? Is there a way to push only the last commit?

I'm not very familiar with css, is the above commit the correct way?

**Comment by Foggalong** [comment]
If the pull requests came from different branches only the commit from that branch should so. Because it isn't, something must have gone wrong.

Looking at the way code has been set out, the CSS needs to be added to the base.html file which all the others inherit rather than this specific one

**Comment by krikmo** [comment]
Should it be inside [this](https://github.com/alexwlchan/hurley/blob/master/hurley/templates/base.html#L53)?

Like this:

```
.container {
        max-width: 800px;
        text-align:center;
    }
```

**Comment by Foggalong** [comment]
Yeah, something like that. Up to @alexwlchan what they want for it though

**Comment by krikmo** [comment]
Of course. Thank you for all the input.

**Comment by alexwlchan** [comment]
Thanks both! :cake: :sparkles: 

@Foggalong I’ll be honest, this is a side project I threw together in an hour or so. If we accidentally used deprecated HTML, I’d live with myself. ;-)

**Pull request merged**
